version: '3'
services:
 db:
     image: techtvm/mysql_techtvm
     container_name: db
     restart: unless-stopped
     environment:
        - MYSQL_ROOT_PASSWORD=Pass@123
     command: '--default-authentication-plugin=mysql_native_password'
     ports:
        - "3306:3306"
     networks:
        - app-network

 php-app:
     depends_on:
        - db
     image: techtvm/php-crud-app
     container_name: php-app
     restart: unless-stopped
     environment:
      - MYSQL_DBHOST=db:3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=Pass@123
      - MYSQL_DBNAME=php_crud
     ports:
       - "8081:80"
     networks:
       - app-network
networks:
  app-network:
   driver: bridge
